### ISSUE TITLE
Bug: Server lag if chunks are pregenerated

### ISSUE THREAD

**Issue by KorDum** [PG85/OpenTerrainGenerator#101]
I have a terrible TPS on my server (3+ players with 66 mods) if I using Biome Bundle 6.1 and pregen 500 chunks. All living entities are moving with pauses. In console without erros, only overloaded warning.
But if don't start (and finish) pregen, all fine.

**Comment by PG85** [comment]
Hey, sorry to disappoint you but pre-generation simply causes lag, it is quite heavy for the server. It is advised to use pre-generation either in single player (and then copy the pre-generated world to a server) or on a server while noone is playing (or only admins are online). Pre-generation is not intended to be used on servers with active players.

**Comment by KorDum** [comment]
No, lags causes AFTER complete pregeneration. TPS 20, but living entities are moving with pauses.
Without pregeneration all ok.

**Comment by KorDum** [comment]
Hmm. Maybe is it related?
https://github.com/PG85/OpenTerrainGenerator/issues/94

**Comment by KorDum** [comment]
```
19:23:12] [LagSpikeProfiler/INFO] [TickProfiler]: 
The server appears to have lag spiked.
Last tick 0.20088643s ago."Server thread" RUNNABLE
        at com.pg85.otg.WorldSession.GetParticlesForChunk(WorldSession.java:157)
        at com.pg85.otg.forge.events.ServerEventListener.findChunksForSpawning(ServerEventListener.java:516)
        at com.pg85.otg.forge.events.ServerEventListener.onServerTick(ServerEventListener.java:618)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_296_ServerEventListener_onServerTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```

Yes, it's duplicate
