### ISSUE TITLE
[1.12.2] Server lag spikes

### ISSUE THREAD

**Issue by KorDum** [PG85/OpenTerrainGenerator#117]
```
[18:02:00] [LagSpikeProfiler/INFO] [TickProfiler]: 
The server appears to have lag spiked.
Last tick 0.20284538s ago."Server thread" RUNNABLE
        at com.pg85.otg.WorldSession.GetSpawnersForChunk(WorldSession.java:123)
        at com.pg85.otg.forge.events.ServerEventListener.findChunksForSpawning(ServerEventListener.java:166)
        at com.pg85.otg.forge.events.ServerEventListener.onServerTick(ServerEventListener.java:618)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_318_ServerEventListener_onServerTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by PG85** [comment]
Hey, thanks for reporting this, that's helpful information. I'll see if I can improve this for the next version.

**Comment by KorDum** [comment]
Thanks! I love your generator!

**Comment by PG85** [comment]
Could you try this and tell me if it fixes the problem? Thanks!
[OTG 1.12.2 v4 - Particles.zip](https://github.com/PG85/OpenTerrainGenerator/files/1647790/OTG.1.12.2.v4.-.Particles.zip)

**Comment by KorDum** [comment]
Thanks!
I installed this version on my server and sent it to all players.
I'll be back later after analyzing the work of the that fixes.

**Comment by KorDum** [comment]
```
Last tick 0.20723236s ago."Server thread" RUNNABLE
        at net.minecraft.world.World.func_175668_a(World.java:239)
        at net.minecraft.world.World.func_175667_e(World.java:234)
        at net.minecraft.world.World.getBiomeForCoordsBody(World.java:153)
        at com.pg85.otg.forge.generator.OTGChunkGenerator.func_177458_a(OTGChunkGenerator.java:274)
        at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:301)
        at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:244)
        at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:127)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```
It's appears only once when player join into game. I think you should not worry about that?
Temp result: 3 players - everything works well.

**Comment by KorDum** [comment]
5 players - OK, without spikes from OTG particles or spawner.

**Comment by KorDum** [comment]
I can say that there were no lags. Thanks!

**Comment by PG85** [comment]
Awesome, thanks for reporting :)
