### ISSUE TITLE
Spigot 1.12.2 - Java 9 crash

### ISSUE THREAD

**Issue by HaydenBelanger** [PG85/OpenTerrainGenerator#121]
Hello,
Your code references a sun dependency that has since been removed since Java 9. Is there any way an alternative could be used so that Java 9 can be used?

```[19:40:33 ERROR]: [OpenTerrainGenerator] Could not set generator for default world 'world': Plugin 'OpenTerrainGenerator v1.12.2 v4
java.lang.ExceptionInInitializerError: null
        at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:131) ~[?:?]
        at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
        at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
        at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
        at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1217) [survival.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:259) [survival.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [survival.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [survival.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
        at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:39) ~[?:?]
        ... 14 more
Caused by: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
        at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
        at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:33) ~[?:?]
        ... 14 more
```

**Comment by Misunderstood-Wookiee** [comment]
Java 9 is not supported by Minecraft yet, many changed methods and new object registration method in JDK9 vs 8, don't expect support soon.

**Comment by PG85** [comment]
Thanks for responding Wookie, will close this issue :).
