### ISSUE TITLE
Crash on server start NoSuchMethodError WorldSettings

### ISSUE THREAD

**Issue by Tototi1** [PG85/OpenTerrainGenerator#139]
When I start server with 1.10.2 biome bundle map, the server crash.
crash report : 
`Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.WorldSettings.func_77166_b()Lnet/minecraft/world/WorldSettings;
	at com.pg85.otg.forge.OTGWorldType.getBiomeProvider(OTGWorldType.java:70)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)`

**Comment by LemADEC** [comment]
This is reproduced with OpenTerrainGenerator-1.12.2 - v6.
Issue is due to the mod calling the client side only method WorldSettings::enableCommands() on a server.

**Comment by CrankySupertoonArchive** [comment]
fix?

**Comment by Barerock** [comment]
Did anyone ever fix this?

**Comment by phillipinman** [comment]
Same issue as well with sponge.

net.minecraft.world.WorldSettings.func_77166_b()Lnet/minecraft/world/WorldSettings

**Comment by LemADEC** [comment]
It's an easy fix, not sure when PG will have time to implement

**Comment by PG85** [comment]
Hey, thanks for reporting. Should be fixed with v7, you can grab a dev build from the OTG Discord at /openterraingen. Cheers.
