### ISSUE TITLE
[Spigot] Issue when Rotating Objects

### ISSUE THREAD

**Issue by LanToaster** [PG85/OpenTerrainGenerator#151]
It appears that OTG has some Issues when Rotating Objects on Spigot 1.12.2

When I tried to load my SkyLands preset on OTG 1.12.2 with Spigot 1.12.2 (to check if it would work together with BB to test the Issue I posted a bit earlier)
I got this Error:

```
[18:48:24] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception initializing level
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:937) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:277) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
	at com.pg85.otg.customobjects.bo3.BlockCheckNot.rotate(BlockCheckNot.java:29) ~[?:?]
	at com.pg85.otg.customobjects.bo3.BO3Config.rotateBlocksAndChecks(BO3Config.java:1358) ~[?:?]
	at com.pg85.otg.customobjects.bo3.BO3Config.<init>(BO3Config.java:860) ~[?:?]
	at com.pg85.otg.customobjects.bo3.BO3.onEnable(BO3.java:1151) ~[?:?]
	at com.pg85.otg.customobjects.CustomObjectCollection.loadObject(CustomObjectCollection.java:62) ~[?:?]
	at com.pg85.otg.customobjects.CustomObjectCollection.getObjectByName(CustomObjectCollection.java:207) ~[?:?]
	at com.pg85.otg.generator.resource.CustomObjectGen.getObjects(CustomObjectGen.java:28) ~[?:?]
	at com.pg85.otg.generator.resource.CustomObjectGen.spawnInChunk(CustomObjectGen.java:66) ~[?:?]
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152) ~[?:?]
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259) ~[?:?]
	at com.pg85.otg.bukkit.generator.OTGBlockPopulator.populate(OTGBlockPopulator.java:30) ~[?:?]
	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:979) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:943) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:173) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:271) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:162) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:104) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getHighestBlockAt(CraftWorld.java:592) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at com.pg85.otg.bukkit.generator.OTGChunkGenerator.canSpawn(OTGChunkGenerator.java:87) ~[?:?]
	at net.minecraft.server.v1_12_R1.WorldServer.canSpawn(WorldServer.java:258) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1000) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:922) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-c3093ef-aa25568]
	... 4 more
```
Sadly, I have no Idea which object this caused on my end.

**Comment by LanToaster** [comment]
I now know what caused this. 
There is a Faulty BlockCheck in one of the Objects.

Maybe it could be a Consideration to Validate Objects and throw an Error if somethings broken.

**Comment by MCPitman** [comment]
Closing this issue as I created a duplicate with a clearer explanation.

**Comment by PG85** [comment]
For v8_r2 this should throw an InvalidConfigException with a description that's logged, this invalidates the blockcheck but not the BO3, and doesn't crash the game.
