### ISSUE TITLE
Primal core: endless loop! issue (otg.generator.resource.TreeGen.spawnInChunk)

### ISSUE THREAD

**Issue by DEX47** [PG85/OpenTerrainGenerator#155]
World generator triggering an endless loop.

OpenTerrainGenerator-1.12.2 - v6
Biome_Bundle-1.12.2-v6.1

> Stacktrace:
	at com.pg85.otg.generator.resource.TreeGen.spawnInChunk(TreeGen.java:153)
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152)
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259)
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:203)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.func_180495_p(World.java:910)
	at net.minecraft.world.World.func_190529_b(World.java:580)
	at net.minecraft.world.World.func_190522_c(World.java:478)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:389)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at nmd.primal.core.common.world.feature.GenMinableSubOre.func_180709_b(GenMinableSubOre.java:95)
	at nmd.primal.core.common.world.WorldGenCommon.generate(WorldGenCommon.java:82)
	at nmd.primal.core.common.world.generators.PrimalWorld.generate(PrimalWorld.java:41)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
>

**Comment by PG85** [comment]
Hey, looks like primalcore is spawning or updating blocks across chunk borders where it shouldn't be, causing cascading chunk population. Could you report this to the PrimalCore devs? Thanks.
