### ISSUE TITLE
Crash upon world start

### ISSUE THREAD

**Issue by Andyghandi** [PG85/OpenTerrainGenerator#163]
From what I can tell in the crash report, it looks like it is related somehow to OTG. So I created a world with your mod, looks fantastic with biome bundle btw, but I experienced some huge lag spikes, which made it unplayable. So i figured taking OTG and biome bundle out from the mod list. But when creating a new world afterwords with BOP, the world simply crashes and i recieve this crash log: 

Time: 4/26/18 5:35 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactorMineCart(OTGHooks.java:36)
	at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:326)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.pg85.otg.forge.dimensions.WorldProviderOTG
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactorMineCart(OTGHooks.java:36)
	at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:326)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:chest_minecart (net.minecraft.entity.item.EntityMinecartChest)
	Entity ID: 356
	Entity Name: Minecart with Chest
	Entity's Exact location: 190.50, 34.50, 155.50
	Entity's Block location: World: (190,34,155), Chunk: (at 14,2,11 in 11,9; contains blocks 176,0,144 to 191,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Test new world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 658 Drop: 0
	Level seed: 1574227800798854869
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (244,64,240), Chunk: (at 4,4,0 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 172512 (now: false), thunder time: 169335 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

So before I installed this mod, BOP worlds worked, and with this mod, it sorta worked, but with lag spikes, and now BOP worlds dont start. Hope the crash report shows anything useful.

**Comment by Andyghandi** [comment]
Using latest forge for 1.12.2 and v6 of OTG and v6.1 of biome bundle

**Comment by Andyghandi** [comment]
Doesn't matter if I use BOP world option, crashes the same way with default. Also checked for others experiencing same behaviour and found this: http://www.minecraftforge.net/forum/topic/63731-game-crashes-at-world-gen/

**Comment by lloyd-alex** [comment]
I have the same issue... 😢

**Comment by MxtressMyxx** [comment]
Same issue here. OTG has been removed but it has polluted something. Even doing clean rebuilds of my modpack, my worlds keep crashing like this. I need to know what OTG changed so I can fix it.

**Comment by CorbinIvon** [comment]
Well, I don't know if you removed the OTG-Core from the 1.12.2 folder located with the rest of the mods, but when I did that, that seems to have fixed the problem for me.

Again, it's located at:
.minecraft->mods->1.12.2 (Or whatever version you may be using)

**Comment by PG85** [comment]
Hey guys, sorry for the late reply. This is indeed OTGCore causing a crash because it cannot find OTG code, removing OTG-Core should solve the problem.

**Comment by bookerthegeek** [comment]
## Heyo
Sorry for necro posting.  Had this same issue and it took a while to find this issue. Can I suggest adding an error message to he crash log explaining about the crash being due to the OTG-Core not finding the normal OTG mod, and if OTG was removed that te OTG-Core also needs to be removed?

Love the mod. I turned i off only temporarily until the pack s built.

**Comment by snowinmars** [comment]
@bookerthegeek I believe that the core of the issue is bad mod manager. It shouldn't allow the mod tree to be broken.

**Comment by bookerthegeek** [comment]
While true that mod managers should also help with this, that does not solve the issue that the core mod is crashing the game and unless you google search you have no idea as to why.

Also I regularly build my packs with multimc and otg will download the core mod automatically. Why would I think to delete a core mod that I did not even know was their in the first place?

**Comment by yaantar** [comment]
I had the same issue,I've deleted OTG-Core and OPG.
After that Minecraft started to work normal.

**Comment by ANerdyNub** [comment]
> Well, I don't know if you removed the OTG-Core from the 1.12.2 folder located with the rest of the mods, but when I did that, that seems to have fixed the problem for me.
> 
> Again, it's located at:
> .minecraft->mods->1.12.2 (Or whatever version you may be using)

thx fixed it :D
