### ISSUE TITLE
When entering a compact machine dimension I get the following crash on server.

### ISSUE THREAD

**Issue by ZiroGX2** [PG85/OpenTerrainGenerator#185]
Description: Exception in server tick loop

`java.lang.NullPointerException
    at com.pg85.otg.forge.events.ServerEventListener.tryTeleportPlayer(ServerEventListener.java:803)
    at com.pg85.otg.forge.events.ServerEventListener.TeleportPlayers(ServerEventListener.java:794)
    at com.pg85.otg.forge.events.ServerEventListener.onServerTick(ServerEventListener.java:606)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1710_ServerEventListener_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:597)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by PG85** [comment]
Hey, thanks for reporting this. Should be fixed with v7.

**Comment by zhourui123** [comment]
Where is v7 download link?  i just find v6 from curseforge

**Comment by Sascha-T** [comment]
^

**Comment by Jishuna** [comment]
You can find v7 (Now v8) on our discord in the #otg-dev channel.
https://discord.gg/UXzdVTH
