### ISSUE TITLE
Unloadable world crash LoadStructureCache

### ISSUE THREAD

**Issue by MCPitman** [PG85/OpenTerrainGenerator#192]
Pre-generated an OTGPlus enabled world in single player that crashed due to running out of memory, the world now cannot be loaded at all and gives this crash on startup:

```
[20:47:25] [Server thread/INFO] [OTG]: Loading structures and pre-generator data
[20:47:25] [Server thread/INFO] [OTG]: Loaded 0 structure chunks
[20:47:25] [Server thread/INFO] [OTG]: Running false L286 R287 T286 B286
[20:47:25] [Server thread/INFO] [OTG]: Error at Chunk X-59 Z-16
[20:47:25] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: null
	at com.pg85.otg.customobjects.CustomObjectStructureCache.LoadStructureCache(CustomObjectStructureCache.java:1339) ~[CustomObjectStructureCache.class:?]
	at com.pg85.otg.customobjects.CustomObjectStructureCache.<init>(CustomObjectStructureCache.java:67) ~[CustomObjectStructureCache.class:?]
	at com.pg85.otg.forge.ForgeWorld.provideWorldInstance(ForgeWorld.java:1250) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:378) ~[WorldLoader.class:?]
	at com.pg85.otg.forge.OTGWorldType.getBiomeProvider(OTGWorldType.java:74) ~[OTGWorldType.class:?]
	at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_76572_b(WorldProviderOTG.java:87) ~[WorldProviderOTG.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) ~[aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) ~[oo.class:?]
	at WorldServerOF.<init>(WorldServerOF.java:25) ~[WorldServerOF.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:94) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by TheForgottenKing** [comment]
Looks like a corrupted chunk, try deleting it?
