### ISSUE TITLE
Feature: 1.13 support

### ISSUE THREAD

**Issue by DmitryRendov** [PG85/OpenTerrainGenerator#204]
Spigot: git-Spigot-2b0e71c-4a24108 (MC: 1.13)
OTG: v1.12.2 v6

`[17:20:49] [Server thread/INFO]: [OpenTerrainGenerator] Enabling OpenTerrainGenerator v1.12.2 v6
[17:20:49] [Server thread/ERROR]: Error occurred while enabling OpenTerrainGenerator v1.12.2 v6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/WorldGenFactory
        at com.pg85.otg.bukkit.OTGPlugin.onEnable(OTGPlugin.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:214) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.WorldGenFactory
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-survival-1.13.jar:git-Spigot-2b0e71c-4a24108]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
        ... 9 more
`

**Comment by MCPitman** [comment]
Are you trying to say that OTG for 1.12.2 does not work with Spigot for 1.13?

Isn't that obvious?

**Comment by DmitryRendov** [comment]
yes, it is. Also, it's a common practice is to raise such issues/milestones to track major upgrades. I'm leaving it here for the github community and search engines just in case, if you make us happy with any news or progress. 

I do appreciate your efforts and will wait for a release as long as it's needed) 
sincerely yours, 
  captain obvious

**Comment by 7kasper** [comment]
I take it there are plans for an update? :-) Is the new world build-in worldgen much of a hassle?

**Comment by jfernandz** [comment]
> I take it there are plans for an update? :-) Is the new world build-in worldgen much of a hassle?

I'm also curious about this :-)

**Comment by PG85** [comment]
Hey folks, I'm still hard at work at OTG 1.12.2 v7 but a new developer (Josh) recently volunteered to take a whack at updating to 1.13. He's just got started and there's still a lot of hurdles that need to be taking, but he seems to be making good progress. Ask questions and join the discussion on our Discord if you'd like to know how things are going.

**Comment by ccorp2002** [comment]
Any news/beta repository I could check out for 1.13.2+?

**Comment by PG85** [comment]
Hey @ccorp2002 , I'll start working on 1.13/1.14/1.15 as soon as v9 is ready, hopefully within a week or two. Join us on the OTG Discord if you have more questions like this, cheers!

**Comment by SXRWahrheit** [comment]
Version progress is announced on Discord and tracked via GitHub milestones, like PG said.

**Comment by PG85** [comment]
We're skipping to 1.16, progress will be tracked via milestones.
