### ISSUE TITLE
Procedure for Removing OTG

### ISSUE THREAD

**Issue by atxmatt2510** [PG85/OpenTerrainGenerator#210]
I've been using OTG for a little while and have decided to remove it due to missing custom biomes. When I delete the mods and restart the Server (with updated server.properties file) I get this crash:

[12:36:27] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: com/pg85/otg/forge/dimensions/WorldProviderOTG
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactorItem(OTGHooks.java:84) ~[OTG-Core.jar:?]
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:110) ~[acl.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.pg85.otg.forge.dimensions.WorldProviderOTG
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at com.pg85.otg.forge.asm.OTGHooks.getGravityFactorItem(OTGHooks.java:84) ~[OTG-Core.jar:?]
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:110) ~[acl.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.NullPointerException
[12:36:27] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: D:\Games\Minecraft Forge - Server\.\crash-reports\crash-2018-11-08_12.36.27-server.txt

**Comment by MCPitman** [comment]
Remove the core mod

**Comment by atxmatt2510** [comment]
You were correct. I failed to notice the mod in the "1.12.2" folder.
