### ISSUE TITLE
Suggestion: Add an error message for when people misspell resource paths within bo3s

### ISSUE THREAD

**Issue by Snorps** [PG85/OpenTerrainGenerator#224]
After misspelling a resource path in a bo3, I got this error
`java.lang.NullPointerException: Exception ticking world
	at com.pg85.otg.customobjects.bo3.BlockFunction.rotate(BlockFunction.java:67)
	at com.pg85.otg.customobjects.bo3.BO3Config.rotateBlocksAndChecks(BO3Config.java:1352)
	at com.pg85.otg.customobjects.bo3.BO3Config.<init>(BO3Config.java:860)
	at com.pg85.otg.customobjects.bo3.BO3.onEnable(BO3.java:1151)
	at com.pg85.otg.customobjects.CustomObjectCollection.loadObject(CustomObjectCollection.java:62)
	at com.pg85.otg.customobjects.CustomObjectCollection.getObjectByName(CustomObjectCollection.java:207)
	at com.pg85.otg.generator.resource.CustomObjectGen.getObjects(CustomObjectGen.java:28)
	at com.pg85.otg.generator.resource.CustomObjectGen.spawnInChunk(CustomObjectGen.java:66)
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152)
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259)
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:203)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)`
I scratched my head over this for a long time before I realized what the issue was. It would be nice to have some kind of error message informing the user that the resource path wasn't recognized as any in game block to make otg more user friendly. 

Thanks,
Snorple

**Comment by PG85** [comment]
Hey @Virtualistik, thanks for the feedback! What kind of resource / resourcepath were you using, a block? And which part of the resourcepath (block tag?) was incorrect?

**Comment by PG85** [comment]
*does not affect Forge or OTG+, still have to check for Spigot

**Comment by PG85** [comment]
Will close this since its so old, feel free to re-open if necessary.
