### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by GoogleTan** [PG85/OpenTerrainGenerator#231]
Server crashed with this log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 04.02.19 5:25
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Open Terrain Generator (openterraingenerator)
Caused by: java.lang.RuntimeException: OTG has detected that you are loading an OTG world that has been used without OTG installed. OTG has fixed and saved the world data, you can now restart the game and enter the world.
	at com.pg85.otg.forge.OTGPlugin.serverLoad(OTGPlugin.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:792)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 603731768 bytes (575 MB) / 790102016 bytes (753 MB) up to 1776812032 bytes (1694 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2810 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                   | Version      | Source                                  | Signature                                |
	|:------- |:-------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft            | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA  | mcp                  | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA  | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2810-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | forge                | 14.23.5.2810 | forge-1.12.2-14.23.5.2810-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | otgcore              | 1.12.2 - v7  | minecraft.jar                           | None                                     |
	| LCHIJAE | openterraingenerator | v6           | OpenTerrainGenerator-1.12.2 - v6.jar    | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LCHIJA  | otgskylands          | 1.0          | OTG-Skylands-1.12.2-v5.jar              | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by PG85** [comment]
Hey, thanks for reporting. The exception message says:

OTG has detected that you are loading an OTG world that has been used without OTG installed. OTG has fixed and saved the world data, you can now restart the game and enter the world.

Have you tried restarting the server and entering the world?

**Comment by PG85** [comment]
Will close this since it's so old.
