### ISSUE TITLE
The plugin is disabled on the server and isn't loading the biomes or structures

### ISSUE THREAD

**Issue by LuffytheRocky** [PG85/OpenTerrainGenerator#235]
Bukkit server, 1.12.2
When I start my server, after watching the tutorial video on the wiki, reading the instructions, and installing it may times over, I STILL get the same error message:
[00:03:08 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[00:03:08 INFO]: Preparing level "Biome Bundle"
[00:03:10 ERROR]: [OpenTerrainGenerator] Could not set generator for default world 'Biome Bundle': Plugin 'OpenTerrainGenerator v1.12.2 v6
java.lang.ExceptionInInitializerError: null
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:131) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1224) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:260) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:39) ~[?:?]
	... 14 more
Caused by: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at java.lang.Class.getDeclaredMethod(Class.java:2476) ~[?:?]
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:33) ~[?:?]
	... 14 more

Does anyone know why this happens, and HOW TO FIX it. Please do not just say it was installed incorrectly, tell me what I can do about it.

**Comment by MCPitman** [comment]
What java version are you using? If you're using a java version later than 8 try downgrading to Java 8
