### ISSUE TITLE
Crash After World Load BlockCheck.rotate

### ISSUE THREAD

**Issue by marikc0** [PG85/OpenTerrainGenerator#248]
Used this the other week with no problems. Now the world loads and crashes immediately after creation a second after you start to be placed in the world.

Version: OpenTerrainGenerator-1.12.2 - v6.jar
MC: 1.12.2
Forge: 14.23.5.2814

[17:54:23] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.pg85.otg.customobjects.bo3.BlockCheck.rotate(BlockCheck.java:56) ~[BlockCheck.class:?]
	at com.pg85.otg.customobjects.bo3.BO3Config.rotateBlocksAndChecks(BO3Config.java:1358) ~[BO3Config.class:?]
	at com.pg85.otg.customobjects.bo3.BO3Config.<init>(BO3Config.java:860) ~[BO3Config.class:?]
	at com.pg85.otg.customobjects.bo3.BO3.onEnable(BO3.java:1151) ~[BO3.class:?]
	at com.pg85.otg.customobjects.CustomObjectCollection.loadObject(CustomObjectCollection.java:62) ~[CustomObjectCollection.class:?]
	at com.pg85.otg.customobjects.CustomObjectCollection.getObjectByName(CustomObjectCollection.java:207) ~[CustomObjectCollection.class:?]
	at com.pg85.otg.generator.resource.TreeGen.getTrees(TreeGen.java:30) ~[TreeGen.class:?]
	at com.pg85.otg.generator.resource.TreeGen.spawnInChunk(TreeGen.java:143) ~[TreeGen.class:?]
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152) ~[Resource.class:?]
	at com.pg85.otg.generator.ObjectSpawner.processResourcesPhase3(ObjectSpawner.java:502) ~[ObjectSpawner.class:?]
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:178) ~[ObjectSpawner.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.populate(OTGChunkGenerator.java:203) ~[OTGChunkGenerator.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1019) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:980) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147) ~[ou.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
[17:54:23] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\SSD Games\MultiMC\instances\Paradigm Server Pack\.minecraft\crash-reports\crash-2019-05-05_17.54.23-server.txt
[17:54:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[17:54:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[17:54:23] [Netty Local Client IO #0/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[17:54:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[17:54:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'OTGWorld'/overworld
[17:54:23] [Netty Local Client IO #0/INFO] [waterstrainer]: Importing waterstrainer_loottables.cfg ...
[17:54:23] [Netty Local Client IO #0/INFO] [waterstrainer]: No errors were found!
[17:54:23] [Client thread/INFO] [journeymap]: Mapping halted in C:\SSD Games\MultiMC\instances\Paradigm Server Pack\.minecraft\journeymap\data\sp\OTGWorld\DIM0
[17:54:23] [Server thread/INFO] [OTG]: Saving structure data
[17:54:23] [Server thread/INFO] [OTG]: SaveToDisk waiting on Populate. Although other mods could be causing this and there may not be any problem, this can potentially cause an endless loop!

**Comment by PG85** [comment]
Hey, thanks for reporting. Looks like a problem with BO3's, some files may have been edited or corrupted. If you're using a pre-made pack, could you try copying over the WorldObjects directory with a new one?

Should definitely add better logging for this and prevent a crash.

*Looks like a problem with BO3's spawned as trees btw
