### ISSUE TITLE
SaplingListener.getSaplingGen ? 

### ISSUE THREAD

**Issue by MultiDemonhunter** [PG85/OpenTerrainGenerator#251]
Time: 5/19/19 9:52 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.pg85.otg.forge.events.SaplingListener.getSaplingGen(SaplingListener.java:288)
	at com.pg85.otg.forge.events.SaplingListener.onSaplingGrow(SaplingListener.java:178)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1816_SaplingListener_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.terraingen.TerrainGen.saplingGrowTree(TerrainGen.java:108)
	at net.minecraft.block.BlockSapling.func_176476_e(BlockSapling.java:78)
	at net.minecraft.block.BlockSapling.func_176478_d(BlockSapling.java:72)
	at net.minecraft.block.BlockSapling.func_180650_b(BlockSapling.java:59)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pg85.otg.forge.events.SaplingListener.getSaplingGen(SaplingListener.java:288)
	at com.pg85.otg.forge.events.SaplingListener.onSaplingGrow(SaplingListener.java:178)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1816_SaplingListener_onSaplingGrow_SaplingGrowTreeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.terraingen.TerrainGen.saplingGrowTree(TerrainGen.java:108)
	at net.minecraft.block.BlockSapling.func_176476_e(BlockSapling.java:78)
	at net.minecraft.block.BlockSapling.func_176478_d(BlockSapling.java:72)
	at net.minecraft.block.BlockSapling.func_180650_b(BlockSapling.java:59)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

**Comment by PG85** [comment]
Should be fixed with v7_r25
