### ISSUE TITLE
Crash with sponge forge server NoSuchMethodError net/minecraft/world/WorldSettings

### ISSUE THREAD

**Issue by ryanwang0521** [PG85/OpenTerrainGenerator#252]
`java.lang.NoSuchMethodError: net.minecraft.world.WorldSettings.func_77166_b()Lnet/minecraft/world/WorldSettings;
	at com.pg85.otg.forge.OTGWorldType.getBiomeProvider(OTGWorldType.java:70) ~[OTGWorldType.class:?]
	at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_76572_b(WorldProviderOTG.java:87) ~[WorldProviderOTG.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) ~[aym.class:?]
	at net.minecraft.world.WorldServer.redirect$onSetWorld$zmd000(WorldServer.java:1694) ~[oo.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) ~[oo.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:802) ~[WorldManager.class:1.12.2-2768-7.1.5]
	at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:630) ~[WorldManager.class:1.12.2-2768-7.1.5]
	at org.spongepowered.common.world.WorldManager.loadWorld(WorldManager.java:571) ~[WorldManager.class:1.12.2-2768-7.1.5]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:813) ~[DimensionManager.class:?]
	at com.pg85.otg.forge.dimensions.OTGDimensionManager.LoadCustomDimensionData(OTGDimensionManager.java:550) ~[OTGDimensionManager.class:?]
	at com.pg85.otg.forge.OTGPlugin.serverLoad(OTGPlugin.java:222) ~[OTGPlugin.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[server.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:792) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

When i create new world then restart the server,my server will get crash
But if i delete Dimensions.txt at Biome Bundle/OpenTerrainGenerator before i reopen the server
server wont get crash and everything is fine.
Is that a bug or somthing i'm doing wrong?

**Comment by PG85** [comment]
Hey, thanks for reporting. Should be fixed with v7, you can grab a dev build from the OTG Discord at /openterraingen. Cheers.

**Comment by UmaiRamen** [comment]
@PG85 How Do I fix this bug since I have V6.

**Comment by UmaiRamen** [comment]
I'm also using it for the server.
