### ISSUE TITLE
[1.11.2] [Forge] Minecraft hangs on creation of a 'biome bundle' world

### ISSUE THREAD

**Issue by Royal-Jelly** [PG85/OpenTerrainGenerator#32]
Here is a small snip-pit from my MultiMC Log: 
[20:20:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at com.khorn.terraincontrol.forge.TXDimensionManager.RemoveTCDims(TXDimensionManager.java:523) ~[TXDimensionManager.class:?]
	at com.khorn.terraincontrol.forge.ForgeWorld.<init>(ForgeWorld.java:155) ~[ForgeWorld.class:?]
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:284) ~[WorldLoader.class:?]
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:262) ~[WorldLoader.class:?]
	at com.khorn.terraincontrol.forge.TXWorldType.getBiomeProvider(TXWorldType.java:67) ~[TXWorldType.class:?]
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58) ~[avf.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) ~[avf.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:112) ~[lw.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:85) ~[cch.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[20:20:49] [Server thread/ERROR]: This crash report has been saved to: /home/royal-jelly/Desktop/Games/MultiMC[0.5.1]/instances/Forged with Maids [1.11.2]/minecraft/crash-reports/crash-2017-06-07_20.20.49-server.txt

And the whole log can be found here : https://paste.ee/p/OoHka

**Comment by Royal-Jelly** [comment]
I have also posted this report over on the biome bundle Github just in case ~

**Comment by PG85** [comment]
Hey, are you using Sponge by any chance?

**Comment by Royal-Jelly** [comment]
I'm not using sponge and i got a reply over on the biome bundle page

I was told they wont be taking bug reports until the 1.11.2 build of OTG has been officially released

and sorry for the faux bug report ~

**Comment by PG85** [comment]
Thanks for the bug report, looks like this is happening with the latest version of forge (13.20.0.2315), the recommended version (13.20.0.2228) should work fine though. Will fix this a.s.a.p.

**Comment by PG85** [comment]
Could you grab the latest dev version from the comment in this post and tell me if that fixes the problem?

https://www.reddit.com/r/openterraingen/comments/6g6zvq/new_otg_releases_for_1102_and_1112/

Thanks!

**Comment by Royal-Jelly** [comment]
I have done what you asked it is going well so far ~ thank you ~

**Comment by PG85** [comment]
Glad to hear it, you're welcome :)
