### ISSUE TITLE
Bug: Internal Error on login with Forge 2315 and OTG 1.11.2-v6

### ISSUE THREAD

**Issue by Iiridayn** [PG85/OpenTerrainGenerator#40]
```
[01:12:10] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[01:12:10] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.network.FMLNetworkEvent$ServerConnectionFromClientEvent@747078ec:
java.lang.NullPointerException
        at com.khorn.terraincontrol.forge.events.PlayerTracker.SendWorldAndBiomeConfigs(PlayerTracker.java:70) ~[PlayerTracker.class:?]
        at com.khorn.terraincontrol.forge.events.PlayerTracker.onConnectionCreated(PlayerTracker.java:35) ~[PlayerTracker.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_255_PlayerTracker_onConnectionCreated_ServerConnectionFromClientEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [er.class:?]                at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[01:12:10] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[01:12:10] [Server thread/ERROR] [FML]: 0: NORMAL
[01:12:10] [Server thread/ERROR] [FML]: 1: ASM: com.khorn.terraincontrol.forge.events.PlayerTracker@5db52cf7 onConnectionCreated(Lnet/minecraftforge/fml/common/network/FMLNetworkEvent$ServerConnectionFromClientEvent;)V
[01:12:10] [Server thread/WARN]: Failed to handle packet for /192.168.1.6:55156
java.lang.NullPointerException
        at com.khorn.terraincontrol.forge.events.PlayerTracker.SendWorldAndBiomeConfigs(PlayerTracker.java:70) ~[PlayerTracker.class:?]
        at com.khorn.terraincontrol.forge.events.PlayerTracker.onConnectionCreated(PlayerTracker.java:35) ~[PlayerTracker.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_255_PlayerTracker_onConnectionCreated_ServerConnectionFromClientEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[er.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[01:12:10] [Server thread/INFO]: *** lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
```

**Comment by PG85** [comment]
Hey @Iiridayn,

This should only happen if the world you're trying to load was not created via OTG. Could this be the case?

**Comment by Pyrofab** [comment]
I have had exactly the same issue with forge 12.18.3.2316 (1.10.2). This issue arise even when the world is created on server startup.

**Comment by PG85** [comment]
Actually I think it was reported the other day that this can be fixed by deleting some saved/cached files somewhere. Asking MCPitman for confirmation atm.

**Comment by PG85** [comment]
Quoting MCPitman: "The problem was that people's server.properties didn't have the correct level name either because their remote host was reverting the file changes or they didn't set it correctly to begin with."
