### ISSUE TITLE
Plugin does not load and crashes before loading the world

### ISSUE THREAD

**Issue by Theroh** [PG85/OpenTerrainGenerator#421]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ ] OTG Mod for Forge
- [x ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
[Spigot 1.12.2]

#### Server/Client Log
[[14:27:22] [Server thread/INFO]: Starting minecraft server version 1.12.2
[14:27:22] [Server thread/INFO]: Loading properties
[14:27:22] [Server thread/INFO]: Default game type: SURVIVAL
[14:27:22] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[14:27:22] [Server thread/INFO]: Debug logging is disabled
[14:27:22] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:27:22] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:27:22] [Server thread/INFO]: Generating keypair
[14:27:22] [Server thread/INFO]: Starting Minecraft server on 158.69.23.73:25571
[14:27:22] [Server thread/INFO]: Using epoll channel type
[14:27:22] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[14:27:22] [Server thread/INFO]: [OpenTerrainGenerator] Loading OpenTerrainGenerator v1.12.2 v8.3
[14:27:22] [Server thread/INFO]: [OpenTerrainGenerator] Enabling OpenTerrainGenerator v1.12.2 v8.3
[14:27:22] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[14:27:22] [Server thread/INFO]: Preparing level "Biome Bundle"
[14:27:22] [Server thread/ERROR]: [OpenTerrainGenerator] Could not set generator for default world 'Biome Bundle': Plugin 'OpenTerrainGenerator v1.12.2 v8.3
java.lang.ExceptionInInitializerError: null
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:179) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:40) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:534) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:475) ~[?:?]
	at com.pg85.otg.network.ServerConfigProvider.createAndRegisterBiome(ServerConfigProvider.java:632) ~[?:?]
	at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:519) ~[?:?]
	at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:208) ~[?:?]
	at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:134) ~[?:?]
	at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:74) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:150) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1224) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:260) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:39) ~[?:?]
	... 15 more
Caused by: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at java.lang.Class.getDeclaredMethod(Class.java:2475) ~[?:?]
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:33) ~[?:?]
	... 15 more
[14:27:22] [Server thread/INFO]: -------- World Settings For [Biome Bundle] --------
[14:27:22] [Server thread/INFO]: Structure Info Saving: true
[14:27:22] [Server thread/INFO]: Mob Spawn Range: 4
[14:27:22] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:27:22] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[14:27:22] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:27:22] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[14:27:22] [Server thread/INFO]: Random Lighting Updates: false
[14:27:22] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[14:27:22] [Server thread/INFO]: Max TNT Explosions: 100
[14:27:22] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:27:22] [Server thread/INFO]: Item Despawn Rate: 6000
[14:27:22] [Server thread/INFO]: Item Merge Radius: 2.5
[14:27:22] [Server thread/INFO]: Arrow Despawn Rate: 1200
[14:27:22] [Server thread/INFO]: View Distance: 10
[14:27:22] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:27:22] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:27:22] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:27:22] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:27:23] [Server thread/INFO]: -------- World Settings For [Biome Bundle_nether] --------
[14:27:23] [Server thread/INFO]: Structure Info Saving: true
[14:27:23] [Server thread/INFO]: Mob Spawn Range: 4
[14:27:23] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[14:27:23] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:27:23] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[14:27:23] [Server thread/INFO]: Random Lighting Updates: false
[14:27:23] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[14:27:23] [Server thread/INFO]: Max TNT Explosions: 100
[14:27:23] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:27:23] [Server thread/INFO]: Item Despawn Rate: 6000
[14:27:23] [Server thread/INFO]: Item Merge Radius: 2.5
[14:27:23] [Server thread/INFO]: Arrow Despawn Rate: 1200
[14:27:23] [Server thread/INFO]: View Distance: 10
[14:27:23] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:27:23] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:27:23] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:27:23] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:27:23] [Server thread/INFO]: -------- World Settings For [Biome Bundle_the_end] --------
[14:27:23] [Server thread/INFO]: Structure Info Saving: true
[14:27:23] [Server thread/INFO]: Mob Spawn Range: 4
[14:27:23] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:27:23] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[14:27:23] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:27:23] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[14:27:23] [Server thread/INFO]: Random Lighting Updates: false
[14:27:23] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[14:27:23] [Server thread/INFO]: Max TNT Explosions: 100
[14:27:23] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:27:23] [Server thread/INFO]: Item Despawn Rate: 6000
[14:27:23] [Server thread/INFO]: Item Merge Radius: 2.5
[14:27:23] [Server thread/INFO]: Arrow Despawn Rate: 1200
[14:27:23] [Server thread/INFO]: View Distance: 10
[14:27:23] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:27:23] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:27:23] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:27:23] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:27:23] [Server thread/INFO]: Preparing start region for level 0 (Seed: 3831058043805457380)
[14:27:24] [Server thread/INFO]: Preparing spawn area: 8%
[14:27:25] [Server thread/INFO]: Preparing spawn area: 21%
[14:27:26] [Server thread/INFO]: Preparing spawn area: 36%
[14:27:27] [Server thread/INFO]: Preparing spawn area: 49%
[14:27:28] [Server thread/INFO]: Preparing spawn area: 64%
[14:27:29] [Server thread/INFO]: Preparing spawn area: 82%
[14:27:30] [Server thread/INFO]: Preparing start region for level 1 (Seed: 3831058043805457380)
[14:27:31] [Server thread/INFO]: Preparing spawn area: 26%
[14:27:32] [Server thread/INFO]: Preparing spawn area: 50%
[14:27:33] [Server thread/INFO]: Preparing spawn area: 69%
[14:27:34] [Server thread/INFO]: Preparing start region for level 2 (Seed: 3831058043805457380)
[14:27:35] [Server thread/INFO]: Preparing spawn area: 67%
[14:27:36] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:27:36] [Server thread/INFO]: Done (13.225s)! For help, type "help" or "?"
]

#### What other plugins are you running?
[None]

#### Description
[I installed the plugin and this error is what I got]

[What did you expect to happen? - Explain what you expected to happen after performing the previously described steps]

[I took every step the wiki said it needs to be taken, but unfortunately the plugin did not work properly]

**Comment by Theroh** [comment]
It needed to use java 8 to work properly, now everything is fine..
