### ISSUE TITLE
[crash] Exception in server tick loop - "This shouldn't happen"

### ISSUE THREAD

**Issue by Andyghandi** [PG85/OpenTerrainGenerator#484]
#### OTG Plugin or Mod

- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version

- [x] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions

[Forge 1.12.2...2847]

#### Server/Client Log
[Description: Exception in server tick loop

java.lang.RuntimeException: This shouldn't happen
    at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:415)
    at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:208)
    at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:134)
    at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:74)
    at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:362)
    at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:146)
    at net.minecraft.world.WorldProvider.init(WorldProvider.java:58)
    at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:132)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:233)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)]

#### What other plugins are you running?
[MC.eternal modpack + a couple of extra favourite mods (Like OTG)]

#### Description
[Already functioning world crashes upon world start and sends me back to start screen (Vanilla fix feature)]

[I was hoping to be able to play minecraft! x(]

**Comment by Andyghandi** [comment]
I find the server tick loop exception to be pretty strange since i don't play on a server

**Comment by Jishuna** [comment]
Minecraft has run internally on a server even in single player for a while now.

**Comment by Andyghandi** [comment]
I think I fixed it. Rolled back some mod versions after the MC eternal update, in order to play in my world again. I think betweenlands added some biomes in the latest update, which made me ran out of biome IDs. And then I rolled back some backups and deleting otg core too.
