### ISSUE TITLE
Not working with Mohist (new cauldron/kettle).

### ISSUE THREAD

**Issue by notsatvrn** [PG85/OpenTerrainGenerator#488]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [x] Other - Latest master build.

#### Forge or Spigot Versions
Mohist (new cauldron) 1.12.2-6b1591b. Forge version 14.23.5.2854. API version 1.12.2-R0.1-SNAPSHOT.

#### What other plugins are you running?
Plugins (24): AuctionHouse, CrazyEnchantments, CustomOreGen, EconomyShopGUI, Essentials, EssentialsChat, GriefPrevention, LuckPerms, mcMMO, MOTD, OldPVP, OpenTerrainGenerator, PlaceholderAPI, PlugMan, SkQuery, Skript, Sleep, TAB, TimeIsMoney, TradeSystem, UltimateStacker, Vault, ViaVersion, WorldBorder

Mods (36): [minecraft, stackie, unloader, netherportalfix, mohist, colorful-sheep, gottagofast, jei, reccomplex, ivtoolkit, roguelike, vanillafix, bettercaves, mcp, gravelminer, lunatriuscore, otgcore, increasemobs, harvest, FML, foamfixcore, randompatches, bedbugs, aiimprovements, environmentalcreepers, login_shield, additionalstructures, foamfix, randomtweaks, friendlyfire, sledgehammer, dirt2path, forge, fastleafdecay, nmsot, phosphor-lighting, movillages, dsurround, orelib, craftingtweaks]

#### Description
I have setup the bukkit.yml for Biome Bundle, and the server.properties aswell.
When launching the server, I get this error:

```
> [12:52:33 WARN]: [OTG] The biome Cold Plains tried to inherit mobs from itself.
> [12:52:33 ERROR]: Could not set generator for default world 'Biome Bundle': Plugin 'OpenTerrainGenerator v1.12.2 v9.0_r8
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:46) ~[NamespacedWrapper.class:1.12.2-6b1591b]
at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:32) ~[NamespacedWrapper.class:1.12.2-6b1591b]
at com.pg85.otg.bukkit.biomes.OTGBiomeBase.createInstance(OTGBiomeBase.java:100) ~[?:?]
at com.pg85.otg.bukkit.biomes.BukkitBiome.forCustomBiome(BukkitBiome.java:40) ~[?:?]
at com.pg85.otg.bukkit.world.BukkitWorld.createBiomeFor(BukkitWorld.java:512) ~[?:?]
at com.pg85.otg.bukkit.world.BukkitWorld.createBiomeFor(BukkitWorld.java:453) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.createAndRegisterBiome(ServerConfigProvider.java:768) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:651) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:228) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:144) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:83) ~[?:?]
at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:151) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1274) [CraftServer.class:1.12.2-6b1591b]
at net.minecraft.world.World.<init>(World.java:222) [amu.class:?]
at net.minecraft.world.WorldServer.<init>(WorldServer.java:140) [oo.class:?]
at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:350) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:316) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

Any help?

**Comment by notsatvrn** [comment]
I cannot use the mod version, because I want my friends to be able to join on vanilla clients.

**Comment by Jishuna** [comment]
We do not support any forge/spigot crossover builds.

**Comment by notsatvrn** [comment]
I want this to stay open in case anybody knows, but I will contact the Mohist devs as this might be a mappings issue.

**Comment by SXRWahrheit** [comment]
Sorry, this can't stay open because it's an unsupported server version. You're welcome to link the ticket elsewhere.
