### ISSUE TITLE
Index Out Of Bounds: -1 (toBiomeConfig)

### ISSUE THREAD

**Issue by MarcatoSound** [PG85/OpenTerrainGenerator#490]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [ ] OTG Mod for Forge
- [X] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [X] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

#### Server/Client Log
`Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
at com.pg85.otg.generator.ChunkProviderOTG.toBiomeConfig(ChunkProviderOTG.java:602) ~[?:?]
at com.pg85.otg.generator.ChunkProviderOTG.biomeFactor(ChunkProviderOTG.java:489) ~[?:?]
at com.pg85.otg.generator.ChunkProviderOTG.generateTerrainNoise(ChunkProviderOTG.java:386) ~[?:?]
at com.pg85.otg.generator.ChunkProviderOTG.generateTerrainA(ChunkProviderOTG.java:179) ~[?:?]
at com.pg85.otg.generator.ChunkProviderOTG.generate(ChunkProviderOTG.java:125) ~[?:?]
at com.pg85.otg.bukkit.generator.OTGChunkGenerator.generateChunkData(OTGChunkGenerator.java:158) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedChunkGenerator.getOrCreateChunk(TimedChunkGenerator.java:93) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:200) ~[patched_1.12.2.jar:git-Paper-1618]
... 12 more `

#### What other plugins are you running?
- BKCommonLib
- LagAssist
- LightCleaner
- WorldBorder
- WorldEdit

#### Description
Long story short, during generation (either via plug or via flying around) the server can ocassionally crash abruptly. Error log reports an index out of bounds exception. It appears to be trying to find a biome with an id of -1 based on what I've seen in the source code. I haven't the slightest clue how a biome with an id of -1 could exist...

This may very likely be a configuration specific issue related to my worldconfig.ini but despite tweaking and attempting to identify incorrectly configured biomes or biome groups I've not found the cause of the issue...

[Just in case, I have provided my worldconfig.ini here.](https://hastebin.com/fugunofova.coffeescript)

Would love to either get some guidance or a fix, as it's cropped up every seed I've used thus far when attempting to generate!

Cheers.

**Comment by PG85** [comment]
Hey @destradious, this is most likely a problem with your configs. For help with configs, please ask on the OTG Discord at https://discord.gg/UXzdVTH, you can also find the latest OTG dev versions there. If you can narrow this down and confirm it's not a config issue but a bug, feel free to reopen this issue, thanks!
