### ISSUE TITLE
CustomStructure Fracturing branches.

### ISSUE THREAD

**Issue by NLBlackEagle** [PG85/OpenTerrainGenerator#509]
#### OTG Plugin or Mod
- [X] OTG Plugin for Spigot

#### OTG Version
- [x] OpenTerrainGenerator-1.12.2_-_v9.0_r9.jar

#### Forge or Spigot Versions
Paper 1618 1.12.2-R0.1

#### Description
I've used 16x16 branches & also tried 8x8 branches in relation to previous OTG branching errors. Both resulted in the same error which is also new to me. It seems OTG grabs a branch, fractures it and spawns it with an offset as shown in the following screenshot:
![afbeelding](https://user-images.githubusercontent.com/4073584/91239217-336da100-e73f-11ea-990d-44406cc78ca9.png)

Here's the minimal version with this error as Dregora comes with a lot of structures to make debugging easier.
https://dregora.com/wp-content/uploads/2020/08/dregora.zip

**Comment by NLBlackEagle** [comment]
Also tested with git-spigot-dcd1643-e60fc34  ( 12.12.2 r0.1 )

+ OTG V9 R7 
+ OTG V9 R6

OTG V9 R5 loads in properly without the structure being fractured.

**Comment by PG85** [comment]
Hey @NLBlackEagle, thanks for reporting this. I've seen this happen, but only at the spawn point, can you confirm this?

**Comment by NLBlackEagle** [comment]
Yeah, confirmed. All Customstructures spawn properly except for the one in the center
![afbeelding](https://user-images.githubusercontent.com/4073584/91461671-8e131400-e889-11ea-9999-503edf493d5c.png)

And the fracturing does happen at 0,y,0
![afbeelding](https://user-images.githubusercontent.com/4073584/91461756-a8e58880-e889-11ea-8d8a-a488a05b7fad.png)

Apart from this there is also a issue with SKULL:1 NBT data within this structure at spawn. I have removed the skulls and replaced them with glow stone for the sake of fixing one issue at a time. I will see if it is related to this issue. and come back on that.

And it is definitely related. Fixing this issue will automatically fix the NBT issue which causes the following error:

`[17:32:08 INFO]: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntitySkull@621d102a) at -4,82,-1 (AIR) where there was no entity tile!
[17:32:08 INFO]: Chunk coordinates: -16,-16
[17:32:08 WARN]: java.lang.Exception
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:728)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.World.setTileEntity(World.java:1995)
[17:32:08 WARN]: [OTG] Skipping tile entity with id skull, cannot be placed at -5,84,9.
[17:32:08 INFO]: Attempted to place a tile entity (net.minecraft.server.v1_12_R1.TileEntitySkull@7be10a22) at -3,84,9 (AIR) where there was no entity tile!
[17:32:08 INFO]: Chunk coordinates: -16,0
[17:32:08 WARN]: java.lang.Exception
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:728)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.World.setTileEntity(World.java:1995)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:519)
[17:32:08 WARN]:        at com.pg85.otg.bukkit.generator.OTGChunkGenerator.setBlock(OTGChunkGenerator.java:217)
[17:32:08 WARN]:        at com.pg85.otg.bukkit.world.BukkitWorld.setBlock(BukkitWorld.java:1826)
[17:32:08 WARN]:        at com.pg85.otg.customobjects.bo3.bo3function.BO3RandomBlockFunction.spawn(BO3RandomBlockFunction.java:159)
[17:32:08 WARN]:        at com.pg85.otg.customobjects.bo3.BO3.trySpawnAt(BO3.java:342)
[17:32:08 WARN]:        at com.pg85.otg.customobjects.structures.bo3.BO3CustomStructure.spawnInChunk(BO3CustomStructure.java:136)
[17:32:08 WARN]:        at com.pg85.otg.generator.resource.CustomStructureGen.spawnInChunk(CustomStructureGen.java:77)
[17:32:08 WARN]:        at com.pg85.otg.generator.resource.Resource.process(Resource.java:160)
[17:32:08 WARN]:        at com.pg85.otg.generator.ObjectSpawner.doPopulate(ObjectSpawner.java:299)
[17:32:08 WARN]:        at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:113)
[17:32:08 WARN]:        at com.pg85.otg.bukkit.generator.OTGBlockPopulator.populate(OTGBlockPopulator.java:31)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:979)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:950)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:173)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:374)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[17:32:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[17:32:08 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:32:08 WARN]: [OTG] Skipping tile entity with id skull, cannot be placed at -3,84,9.`

**Comment by PG85** [comment]
Awesome, thanks for testing and making the test world. Looks like it might be a problem with the spawn point being moved after generating the first chunk(s), i've had to handle a similar issue for Forge (a p.i.t.a. unfortunately). Looking at this for v9_r10.

**Comment by NLBlackEagle** [comment]
Thanks for your hard work! I will see forward to a fix.

**Comment by PG85** [comment]
fixed for v9_r10
