### ISSUE TITLE
server thread FATAL: Could not find biome with name (biomename) from biome group (biomegroup)

### ISSUE THREAD

**Issue by rakostep** [PG85/OpenTerrainGenerator#596]
#### OTG Plugin or Mod
- [ x ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
- [ x ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [ ] Other - specify here

#### Forge or Spigot Versions
forge-1.12.2-14.23.5.2854

#### Server/Client Log
[The full latest.log file from your server or game client, especially important if you have a stack trace]
```
14.01 03:03:12 [Server] Server thread/INFO [OTG]: Creating world "overworld"
14.01 03:03:12 [Server] Server thread/WARN [OTG]: Biome sandstar_volcano not found for InheritMobsFromBiomeName in Sandstar Volcano.bc
14.01 03:03:12 [Server] Server thread/WARN [OTG]: Biome  Plains not found for InheritMobsFromBiomeName in Sandstar Volcano.bc
14.01 03:03:12 [Server] Server thread/FATAL [OTG]: Could not find biome with name 'Forest' from biome group NormalBiomes
14.01 03:03:12 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
14.01 03:03:12 [Server] INFO java.lang.RuntimeException: Could not find biome with name 'Forest' from biome group NormalBiomes
14.01 03:03:12 [Server] INFO at com.pg85.otg.configuration.biome.BiomeGroup.processBiomeData(BiomeGroup.java:104) ~[BiomeGroup.class:?]
14.01 03:03:12 [Server] INFO at com.pg85.otg.configuration.biome.BiomeGroupManager.processBiomeData(BiomeGroupManager.java:176) ~[BiomeGroupManager.class:?]
14.01 03:03:12 [Server] INFO at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:149) ~[ServerConfigProvider.class:?]
14.01 03:03:12 [Server] INFO at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:84) ~[ServerConfigProvider.class:?]
14.01 03:03:12 [Server] INFO at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:360) ~[WorldLoader.class:?]
14.01 03:03:12 [Server] INFO at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:158) ~[OTGWorldType.class:?]
14.01 03:03:12 [Server] INFO at net.minecraft.world.WorldProvider.init(WorldProvider.java:58) ~[aym.class:?]
14.01 03:03:12 [Server] INFO at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40) ~[aym.class:?]
14.01 03:03:12 [Server] INFO at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) ~[oo.class:?]
14.01 03:03:12 [Server] INFO at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298) ~[MinecraftServer.class:?]
14.01 03:03:12 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) ~[nz.class:?]
14.01 03:03:12 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
14.01 03:03:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
14.01 03:03:12 [Server] Server thread/ERROR [minecraft/MinecraftServer]: This crash report has been saved to: /./crash-reports/crash-2021-01-13_22.03.12-server.txt
14.01 03:03:12 [Server] Server thread/INFO [minecraft/MinecraftServer]: Stopping server
14.01 03:03:12 [Server] Server thread/INFO [minecraft/MinecraftServer]: Saving players
14.01 03:03:12 [Server] Server thread/INFO [minecraft/MinecraftServer]: Saving worlds
14.01 03:03:12 [Server] Server thread/INFO [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
14.01 03:03:12 [Server] Server Shutdown Thread/INFO [minecraft/MinecraftServer]: Stopping server
14.01 03:03:12 [Server] Server Shutdown Thread/INFO [minecraft/MinecraftServer]: Saving players
14.01 03:03:12 [Server] Server Shutdown Thread/INFO [minecraft/MinecraftServer]: Saving worlds
14.01 03:03:13 [Multicraft] Server shut down (running)
14.01 03:03:13 [Multicraft] Restarting crashed server in 10 seconds
14.01 03:03:13 [Multicraft] Server stopped
```

#### Description
I assume it's OTG not being able to find a biome ID for some reason, been swapping around different presets and the result is all the same, it will say that it can't find the biome from the biome group.
It processes smoothly if I remove a biome name that's mentioned but it gets the same error on the next biome in the biomegroup (in WorldConfig.ini)
Tested it now with just OTG installed and now it says it can't find the biome in vanilla minecraft.

**Comment by PG85** [comment]
Update OTG and delete OTG-core.jar. If it still doesn't work, your preset files may contain errors or be corrupted. If you have questions or problems like this, especially when concerning config settings, join us on the Discord as there are more users there who can help. Cheers.
