### ISSUE TITLE
Incompatibility with Dynamic Surroundings

### ISSUE THREAD

**Issue by 1nd1r4** [PG85/OpenTerrainGenerator#601]
#### OTG Plugin or Mod
[Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []]
- [X ] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### OTG Version
[Please specify the full OTG version that you are running by placing "x" into []]
- [ ] 1.12.2_v8_r1
- [ ] 1.12.2_v7_DEV_r26
- [ ] 1.12.2-v6
- [ ] 1.12.2-v5
- [ ] 1.11.2-v8
- [ ] 1.11.2-v9
- [ ] 1.10.2-v21
- [X ] 1.16.4-0.0.3

#### Forge or Spigot Versions
36.0.10

#### Server/Client Log
http://t.ni-td.net/modlog/latest.log

#### What other plugins are you running?
See log: http://t.ni-td.net/modlog/latest.log

#### Description
After creating the world minecraft crashes without rendering a single chunk

Minecraft should have rendered the world

**Comment by authvin** [comment]
This looks like a java version error, I can't find any OTG crashes in the log

```
Java.lang.UnsupportedClassVersionError: org/openjdk/nashorn/api/scripting/NashornScriptEngineFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51] {}
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51] {}
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_51] {}
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_51] {}
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_51] {}
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_51] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51] {}
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
```

**Comment by 1nd1r4** [comment]
> 
> 
> This looks like a java version error, I can't find any OTG crashes in the log
> 
> ```
> Java.lang.UnsupportedClassVersionError: org/openjdk/nashorn/api/scripting/NashornScriptEngineFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51] {}
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51] {}
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_51] {}
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_51] {}
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_51] {}
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_51] {}
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51] {}
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_51] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_51] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
> ```

I use the newest version of JRE 8 64-Bit this is wierd...

**Comment by authvin** [comment]
What's your java version? It looks like you are running 8u51, and the newest is 8u281

**Comment by 1nd1r4** [comment]
> 
> 
> What's your java version? It looks like you are running 8u51, and the newest is 8u281

Found the problem: The mod "Dynamic Surroundings" is causing this error. I have no clue why but thats the cause.
