### ISSUE TITLE
/otg map is broken on 0.0.11

### ISSUE THREAD

**Issue by TheForgottenKing** [PG85/OpenTerrainGenerator#635]
Paperspigot 1.16.5 build 169. The command /otg map worked on 0.0.10 but resulted in a small image, now it sends an error.

No other plugins that seem relevant, but here's the list

```
ChatControl-Free-5.9.1.jar
ChatMessenger.jar
ClearLag.jar
ConsoleSpamFix-1.8.5.jar
EntityTrackerFixer.jar
FastAsyncWorldEdit-Bukkit-1.16-680.jar
GhostMute.jar
Green.jar
HorseTpWithMe-7.4.0.2.jar
IllegalStack-2.2.1a.jar
LuckPerms-Bukkit-5.2.76.jar
LuckPerms-GUI.jar
Multiverse-Core-4.2.2.jar
NoCheatPlus.jar
NoChunkLag.jar
OpenTerrainGenerator-1.16.5-0.0.11.jar
PartyChat-4.0.1.jar
ProtocolLib.jar
RandomSpawn-2.7.2.jar
SimpleTpa-5.3.jar
SuicideKill-1.3.jar
TCPShield-2.4.jar
ViaBackwards-3.2.0.jar
ViaVersion-3.2.1.jar
VoidGenerator-1.7.0.jar
```

And here's the error message every time /otg map is run

```
org.bukkit.command.CommandException: Unhandled exception executing command 'otg' in plugin OpenTerrainGenerator v1.16.5-0.0.11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-669]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-669]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2176) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:

git-Paper-669]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1392) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-669]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-669]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
        at sun.awt.image.IntegerInterleavedRaster.setDataElements(IntegerInterleavedRaster.java:297) ~[?:?]
        at java.awt.image.BufferedImage.setRGB(BufferedImage.java:1016) ~[?:?]
        at com.pg85.otg.spigot.commands.OTGCommandExecutor.mapBiomes(OTGCommandExecutor.java:111) ~[?:?]
        at com.pg85.otg.spigot.commands.OTGCommandExecutor.onCommand(OTGCommandExecutor.java:45) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-669]
        ... 19 more
```

**Comment by PG85** [comment]
Should be fixed for 0.0.12.
