### ISSUE TITLE
OTG + Extra planets: Crash with 1.10.2 v22 rc1 and Extra Planets mod 0.6.9

### ISSUE THREAD

**Issue by chezpaul** [PG85/OpenTerrainGenerator#68]
Thanks for looking into this.

These two mods don't like each other.
When I add Extra Planet to my server, the server will load the first time but if I stop it, then it will never launch again. Instead it crashes with [this error ](https://github.com/MJRLegends/ExtraPlanets/issues/137)(posted on Extra Planets GitHub)

This is the server log on first launch with no problems: [https://pastebin.com/eZxDE3it](https://pastebin.com/eZxDE3it)

The Extraplanet dev left an answer on github
He says: This crash is due to another mod

[13:06:46] [Server thread/INFO] [OTG]: Creating world "Biome Bundle"
[13:06:46] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
at com.khorn.terraincontrol.forge.ForgeEngine.unRegisterForgeBiome(ForgeEngine.java:55) ~[ForgeEngine.class:?]
terraincontrol the issue mod

**Comment by chezpaul** [comment]
Any other mod I try to use that has a new dimension or new biomes crashes my server on the second launch... It's so annoying. Am I stuck to not having any new dimensions?

This was with NetherFx added.

[22:27:01] [Server thread/INFO] [FML]: Applying holder lookups
[22:27:01] [Server thread/INFO] [FML]: Holder lookups applied
[22:27:01] [Server thread/INFO] [OTG]: Creating world "Biome Bundle"
[22:27:01] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at com.khorn.terraincontrol.forge.ForgeEngine.unRegisterForgeBiome(ForgeEngine.java:55) ~[ForgeEngine.class:?]
	at com.khorn.terraincontrol.forge.WorldLoader.unRegisterDefaultBiomes(WorldLoader.java:472) ~[WorldLoader.class:?]
	at com.khorn.terraincontrol.forge.ForgeWorld.<init>(ForgeWorld.java:147) ~[ForgeWorld.class:?]
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:284) ~[WorldLoader.class:?]
	at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:262) ~[WorldLoader.class:?]
	at com.khorn.terraincontrol.forge.TXWorldType.getBiomeProvider(TXWorldType.java:66) ~[TXWorldType.class:?]
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:56) ~[atl.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39) ~[atl.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:113) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:252) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[22:27:01] [Server thread/ERROR]: This crash report has been saved to: /Users/bwayserver/Desktop/Sponge/./crash-reports/crash-2017-10-18_22.27.01-server.txt
[22:27:01] [Server thread/INFO]: Stopping server

**Comment by PG85** [comment]
Hey, thanks for reporting this and sorry for the late reply. v7 uses dynamic biome ids for new worlds so should prevent these problems.
