### ISSUE TITLE
Bug - Using Ore() for >16 veins is impossible, where 16 causes crashes and < 16 works fine.

### ISSUE THREAD

**Issue by PersonTheCat** [PG85/OpenTerrainGenerator#74]
Edit: This only occurs in air, as far as I know. But stone seems fine, which is now obvious to me.

**Comment by PG85** [comment]
Hey, thanks for reporting this. Will see when I can improve this to at least not crash and/or add a note in the documentation.

**Comment by PG85** [comment]
Will need to create a test world and get a crash report. Will do after v7 since it probably won't affect many people.

**Comment by MCPitman** [comment]
```
[21:57:11] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.RuntimeException: Whatever it is you're trying to do, we didn't write any code for it (sorry). Please contact Team OTG about this crash.
    at com.pg85.otg.forge.ForgeWorld.setBlock(ForgeWorld.java:841) ~[ForgeWorld.class:?]
    at com.pg85.otg.generator.resource.OreGen.spawn(OreGen.java:128) ~[OreGen.class:?]
    at com.pg85.otg.generator.resource.Resource.spawnInChunk(Resource.java:195) ~[Resource.class:?]
    at com.pg85.otg.generator.resource.Resource.process(Resource.java:152) ~[Resource.class:?]
    at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259) ~[ObjectSpawner.class:?]
    at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:203) ~[OTGChunkGenerator.class:?]
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) ~[axw.class:?]
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186) ~[chd.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) ~[chd.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

Followed by everyone's favourite, impossible to pin down savetodiskloop:

`[21:57:16] [Server thread/INFO] [OTG]: SaveToDisk waiting on Populate. Although other mods could be causing this and there may not be any problem, this can potentially cause an endless loop!`

All just from putting this in the resource queue: `Ore(STONE:1,48,10,100.0,0,256,AIR)` while `Ore(STONE:1,48,10,100.0,0,256,STONE)` causes no issues.

**Comment by PG85** [comment]
Won't cause a crash anymore for v8_r2
