### ISSUE TITLE
(v1.12.2 v1) Using ReplaceToBiomeName causes an java.lang.AssertionError

### ISSUE THREAD

**Issue by KPWhiver** [PG85/OpenTerrainGenerator#78]
When using "ReplaceToBiomeName: Desert" (or any other vanilla biome besides Desert) in a custom biome with id 201 the following error is printed on startup:

`[18:44:05 ERROR]: [OpenTerrainGenerator] Could not set generator for default world 'world': Plugin 'OpenTerrainGenerator v1.12.2 v1
java.lang.AssertionError: Biome ID #2 returns custom biome #201 instead of its own.
        at com.pg85.otg.bukkit.OTGBiomeBase.checkRegistry(OTGBiomeBase.java:153) ~[?:?]
        at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:141) ~[?:?]
        at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
        at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
        at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1642) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
        at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
        at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1227) [spigot-1.12.2-R0.1-SNAPSHOT-b1442.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:260) [spigot-1.12.2-R0.1-SNAPSHOT-b1442.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2-R0.1-SNAPSHOT-b1442.jar:git-Spigot-d21162c-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT-b1442.jar:git-Spigot-d21162c-61e0c69]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

This is using:
- Spigot:  1.12.2-b1442
- OTG:  v1.12.2 v1

**Comment by PG85** [comment]
Hey there, thanks for reporting this. This is actually not a bug, just a poorly documented feature. You'll have to use a biome id >255 for custom biomes that use ReplaceToBiomeName. Will improve the documentation a.s.a.p.
