### ISSUE TITLE
server itself turned off

### ISSUE THREAD

**Issue by KsenikPL** [PG85/OpenTerrainGenerator#86]
I have problem with you plugin.
today I had the start of the server on which is the openterraingenerator and when the map started to generate, the server itself turned off

[20:50:10] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:812) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-65e8124-357b573]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
    at com.pg85.otg.customobjects.bo3.BlockFunction.rotate(BlockFunction.java:67) ~[?:?]
    at com.pg85.otg.customobjects.bo3.BO3Config.rotateBlocksAndChecks(BO3Config.java:1352) ~[?:?]
    at com.pg85.otg.customobjects.bo3.BO3Config.<init>(BO3Config.java:860) ~[?:?]
    at com.pg85.otg.customobjects.bo3.BO3.onEnable(BO3.java:1151) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectCollection.loadObject(CustomObjectCollection.java:62) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectCollection.getObjectByName(CustomObjectCollection.java:207) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectCoordinate.getObject(CustomObjectCoordinate.java:79) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectCoordinate.getPopulatingChunk(CustomObjectCoordinate.java:229) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectStructure.addToSpawnList(CustomObjectStructure.java:6205) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectStructure.addBranches(CustomObjectStructure.java:6182) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectStructure.addBranches(CustomObjectStructure.java:6187) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectStructure.addBranches(CustomObjectStructure.java:6187) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectStructure.<init>(CustomObjectStructure.java:6159) ~[?:?]
    at com.pg85.otg.customobjects.CustomObjectStructureCache.getStructureStart(CustomObjectStructureCache.java:105) ~[?:?]
    at com.pg85.otg.generator.resource.CustomStructureGen.spawnInChunk(CustomStructureGen.java:81) ~[?:?]
    at com.pg85.otg.generator.resource.Resource.process(Resource.java:152) ~[?:?]
    at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:258) ~[?:?]
    at com.pg85.otg.bukkit.generator.OTGBlockPopulator.populate(OTGBlockPopulator.java:30) ~[?:?]
    at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:979) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:950) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:173) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:112) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:169) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:316) ~[server.jar:git-Spigot-65e8124-357b573]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) ~[server.jar:git-Spigot-65e8124-357b573]

**Comment by PG85** [comment]
Hey, thanks for reporting. This is the same issue as: #97
