### ISSUE TITLE
1.12.2 mixing biome bundle + OTG with TwilightForest crash

### ISSUE THREAD

**Issue by croftyraider** [PG85/OpenTerrainGenerator#87]
Testing the combo out and attempting to leave the overworld to go to the TwilightForest does this:

`[16:48:49] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Colliding entity with block
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:194) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassCastException: com.pg85.otg.forge.generator.OTGBiome cannot be cast to net.minecraft.world.biome.BiomeForest
	at twilightforest.biomes.TFBiomeFireflyForest.func_180624_a(TFBiomeFireflyForest.java:46) ~[TFBiomeFireflyForest.class:?]
	at twilightforest.world.ChunkGeneratorTwilightForest.func_185931_b(ChunkGeneratorTwilightForest.java:812) ~[ChunkGeneratorTwilightForest.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:309) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:304) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:910) ~[amu.class:?]
	at twilightforest.TFTeleporter.func_180620_b(TFTeleporter.java:133) ~[TFTeleporter.class:?]
	at twilightforest.TFTeleporter.func_180266_a(TFTeleporter.java:43) ~[TFTeleporter.class:?]
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:707) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:617) ~[pl.class:?]
	at twilightforest.block.BlockTFPortal.func_180634_a(BlockTFPortal.java:225) ~[BlockTFPortal.class:?]
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1042) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1946) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2381) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) ~[oz.class:?]
	... 5 more`

**Comment by croftyraider** [comment]
Close this if you wish please - there is an identical issue on the Biome Bundle github issue tracker.
