### ISSUE TITLE
Issue: OTG Crash On startup

### ISSUE THREAD

**Issue by TandJ21** [PG85/OpenTerrainGenerator#89]
[06:27:09] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[06:27:09] [main/INFO] [FML/]: Forge Mod Loader version 14.23.1.2559 for Minecraft 1.12.2 loading
[06:27:09] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_151, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_151
[06:27:09] [main/DEBUG] [FML/]: Java classpath at launch is:
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\minecraftforge\forge\1.12.2-14.23.1.2559\forge-1.12.2-14.23.1.2559.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\jline\jline\2.13\jline-2.13.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\mojang\patchy\1.1\patchy-1.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\21.0\guava-21.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\mojang\realms\1.10.17\realms-1.10.17.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\versions\1.12.2\1.12.2.jar
[06:27:09] [main/DEBUG] [FML/]: Java library path at launch is:
[06:27:09] [main/DEBUG] [FML/]:     C:\Users\7305\Documents\Curse\Minecraft\Install\versions\forge-14.23.1.2559\forge-14.23.1.2559-natives-880745037071676
[06:27:09] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[06:27:09] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[06:27:09] [main/DEBUG] [FML/]: Found signing certificates for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin)
[06:27:09] [main/DEBUG] [FML/]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[06:27:09] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[06:27:09] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[06:27:09] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[06:27:09] [main/DEBUG] [FML/]: Found signing certificates for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin)
[06:27:09] [main/DEBUG] [FML/]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[06:27:09] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[06:27:09] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[06:27:09] [main/DEBUG] [FML/]: Extracting ContainedDep OTG-Core.jar from C:\Users\7305\Documents\Curse\Minecraft\Instances\Yet To Be Named\mods\OpenTerrainGenerator-1.12.2 - v2.jar to C:\Users\7305\Documents\Curse\Minecraft\Instances\Yet To Be Named\mods\OTG-Core.jar
[06:27:09] [main/DEBUG] [FML/]: Extracted ContainedDep OTG-Core.jar from C:\Users\7305\Documents\Curse\Minecraft\Instances\Yet To Be Named\mods\OpenTerrainGenerator-1.12.2 - v2.jar to C:\Users\7305\Documents\Curse\Minecraft\Instances\Yet To Be Named\mods\OTG-Core.jar
[06:27:09] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to C:\Users\7305\Documents\Curse\Minecraft\Instances\Yet To Be Named
[06:27:09] [main/DEBUG] [FML/]: Discovering coremods
[06:27:09] [main/DEBUG] [FML/]: Examining for coremod candidacy Biome_Bundle-1.12.2-v6.1.jar
[06:27:09] [main/DEBUG] [FML/]: Not found coremod data in Biome_Bundle-1.12.2-v6.1.jar
[06:27:09] [main/DEBUG] [FML/]: Examining for coremod candidacy OpenTerrainGenerator-1.12.2 - v2.jar
[06:27:09] [main/DEBUG] [FML/]: Not found coremod data in OpenTerrainGenerator-1.12.2 - v2.jar
[06:27:09] [main/DEBUG] [FML/]: Examining for coremod candidacy OTG ASM-1.12.2 - v1.jar
[06:27:09] [main/TRACE] [FML/]: Adding OTG ASM-1.12.2 - v1.jar to the list of known coremods, it will not be examined again
[06:27:09] [main/DEBUG] [FML/]: Instantiating coremod class OTGASMPlugin
[06:27:09] [main/DEBUG] [FML/]: The coremod com.pg85.otg.asm.launch.OTGASMPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[06:27:09] [main/WARN] [FML/]: The coremod OTGASMPlugin (com.pg85.otg.asm.launch.OTGASMPlugin) is not signed!
[06:27:09] [main/DEBUG] [FML/]: Enqueued coremod OTGASMPlugin
[06:27:09] [main/DEBUG] [FML/]: Examining for coremod candidacy OTG-Core.jar
[06:27:09] [main/TRACE] [FML/]: Adding OTG-Core.jar to the list of known coremods, it will not be examined again
[06:27:09] [main/DEBUG] [FML/]: Instantiating coremod class OTGASMPlugin
[06:27:09] [main/DEBUG] [FML/]: The coremod com.pg85.otg.forge.asm.launch.OTGASMPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[06:27:09] [main/WARN] [FML/]: The coremod OTGASMPlugin (com.pg85.otg.forge.asm.launch.OTGASMPlugin) is not signed!
[06:27:09] [main/DEBUG] [FML/]: Enqueued coremod OTGASMPlugin
[06:27:09] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:27:09] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[06:27:09] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:27:09] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:27:09] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:27:09] [main/DEBUG] [FML/]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[06:27:09] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[06:27:09] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[06:27:09] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[06:27:09] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[06:27:09] [main/DEBUG] [FML/]: Injection complete
[06:27:09] [main/DEBUG] [FML/]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[06:27:09] [main/DEBUG] [FML/]: Running coremod plugin FMLCorePlugin
[06:27:11] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[06:27:11] [main/DEBUG] [FML/]: Read 1033 binary patches
[06:27:11] [main/DEBUG] [FML/]: Loading deobfuscation resource /deobfuscation_data-1.12.2.lzma with 36083 records
[06:27:12] [main/INFO] [FML/]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[06:27:12] [main/INFO] [FML/]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[06:27:12] [main/DEBUG] [FML/]: Coremod plugin class FMLCorePlugin run successfully
[06:27:12] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:27:12] [main/DEBUG] [FML/]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[06:27:12] [main/DEBUG] [FML/]: Injection complete
[06:27:12] [main/DEBUG] [FML/]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[06:27:12] [main/DEBUG] [FML/]: Running coremod plugin FMLForgePlugin
[06:27:12] [main/DEBUG] [FML/]: Coremod plugin class FMLForgePlugin run successfully
[06:27:12] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:27:12] [main/DEBUG] [FML/]: Injecting coremod OTGASMPlugin \{com.pg85.otg.asm.launch.OTGASMPlugin\} class transformers
[06:27:12] [main/TRACE] [FML/]: Registering transformer com.pg85.otg.asm.OTGClassTransformer
[06:27:12] [main/DEBUG] [FML/]: Injection complete
[06:27:12] [main/DEBUG] [FML/]: Running coremod plugin for OTGASMPlugin \{com.pg85.otg.asm.launch.OTGASMPlugin\}
[06:27:12] [main/DEBUG] [FML/]: Running coremod plugin OTGASMPlugin
[06:27:12] [main/DEBUG] [FML/]: Coremod plugin class OTGASMPlugin run successfully
[06:27:12] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:27:12] [main/DEBUG] [FML/]: Injecting coremod OTGASMPlugin \{com.pg85.otg.forge.asm.launch.OTGASMPlugin\} class transformers
[06:27:12] [main/TRACE] [FML/]: Registering transformer com.pg85.otg.forge.asm.OTGClassTransformer
[06:27:12] [main/DEBUG] [FML/]: Injection complete
[06:27:12] [main/DEBUG] [FML/]: Running coremod plugin for OTGASMPlugin \{com.pg85.otg.forge.asm.launch.OTGASMPlugin\}
[06:27:12] [main/DEBUG] [FML/]: Running coremod plugin OTGASMPlugin
[06:27:12] [main/DEBUG] [FML/]: Coremod plugin class OTGASMPlugin run successfully
[06:27:12] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[06:27:12] [main/DEBUG] [FML/]: Loaded 208 rules from AccessTransformer config file forge_at.cfg
[06:27:12] [main/DEBUG] [FML/]: Loaded 8 rules from AccessTransformer mod jar file C:\Users\7305\Documents\Curse\Minecraft\Instances\Yet To Be Named\mods\OpenTerrainGenerator-1.12.2 - v2.jar!META-INF/openterraingenerator_at.cfg

[06:27:12] [main/DEBUG] [FML/]: Validating minecraft
[06:27:13] [main/DEBUG] [FML/]: Minecraft validated, launching...
[06:27:13] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[06:27:13] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[06:27:13] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[06:27:15] [main/INFO] [STDOUT/]: [com.pg85.otg.asm.OTGClassTransformer:transform:55]: Transforming: net.minecraftforge.registries.GameData
[06:27:15] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/registries/GameData
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.registries.GameData
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.pg85.otg.asm.OTGClassTransformer@62d73ead from coremod OTGASMPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.1.2559.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: scala/tools/asm/Type
	at com.pg85.otg.asm.OTGClassTransformer.transformInjectSnapshot(OTGClassTransformer.java:275) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at com.pg85.otg.asm.OTGClassTransformer.transform(OTGClassTransformer.java:66) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at com.pg85.otg.asm.OTGClassTransformer.transform(OTGClassTransformer.java:48) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.1.2559.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: scala.tools.asm.Type
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at com.pg85.otg.asm.OTGClassTransformer.transformInjectSnapshot(OTGClassTransformer.java:275) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at com.pg85.otg.asm.OTGClassTransformer.transform(OTGClassTransformer.java:66) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at com.pg85.otg.asm.OTGClassTransformer.transform(OTGClassTransformer.java:48) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.1.2559.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at com.pg85.otg.asm.OTGClassTransformer.transformInjectSnapshot(OTGClassTransformer.java:275) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at com.pg85.otg.asm.OTGClassTransformer.transform(OTGClassTransformer.java:66) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at com.pg85.otg.asm.OTGClassTransformer.transform(OTGClassTransformer.java:48) ~[OTG%20ASM-1.12.2%20-%20v1.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.1.2559.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[06:27:15] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TandJ21** [comment]
seems like its failing to get otg core jar cos i have tried with and without otg asm and getting the same crash

**Comment by TandJ21** [comment]
and i have even tried the older version of otg that needed the asm and still getting same crash

**Comment by TandJ21** [comment]
this issue is still ongoing for me and have no idea how to fix it or what to do about it

**Comment by PG85** [comment]
Hey, if you remove OTG-ASM.jar and only have the newest OTG jar it should work (it should unpack otg-core.jar automatically). If that does not solve it then could it be that you are using some kind of non-standard minecraft setup or mod development environment?

**Comment by TandJ21** [comment]
im using mineraft from the curse / twitch launcher and i have tried the latest version of otg and still get the same crash

**Comment by PG85** [comment]
Hmm, could you try it with OTG 1.12.2 - v3 and the recommended forge version (1.12.2 - 14.23.1.2555) and see if you get the same problem?

**Comment by PG85** [comment]
Will close this now, feel free to reopen if the issue remains,
