### ISSUE TITLE
Coral Resource Crashing

### ISSUE THREAD

**Issue by LordSmellyPants** [PG85/OpenTerrainGenerator#904]
Using coral resource, placing coral at a non-standard height causes a crash. Having the bed of Ocean at y3 caused a crash, at y15 it didn't. Ocean height min 0 max 12. 

**Biome crashing:** Alien Lakes
**OTG version:** OpenTerrainGenerator-1.16.5-0.1.2
Biome pack attached 

<details>
  <summary>Crash Report!</summary>
`java.lang.NullPointerException: Biome decoration
	at com.pg85.otg.gen.resource.util.CoralHelper.placeCoralBlock(CoralHelper.java:28) ~[?:1.16.5-0.1.2] {re:classloading}
	at com.pg85.otg.gen.resource.CoralMushroomResource.spawn(CoralMushroomResource.java:48) ~[?:1.16.5-0.1.2] {re:classloading}
	at com.pg85.otg.gen.resource.FrequencyResourceBase.spawnForChunkDecoration(FrequencyResourceBase.java:42) ~[?:1.16.5-0.1.2] {re:classloading}
	at com.pg85.otg.gen.resource.IBasicResource.processForChunkDecoration(IBasicResource.java:24) ~[?:1.16.5-0.1.2] {re:classloading}
	at com.pg85.otg.gen.OTGChunkDecorator.doDecorate(OTGChunkDecorator.java:199) ~[?:1.16.5-0.1.2] {re:classloading}
	at com.pg85.otg.gen.OTGChunkDecorator.decorate(OTGChunkDecorator.java:118) ~[?:1.16.5-0.1.2] {re:classloading}
	at com.pg85.otg.forge.gen.OTGNoiseChunkGenerator.func_230351_a_(OTGNoiseChunkGenerator.java:607) ~[?:1.16.5-0.1.2] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:otg.mixins.json:MixinChunkManager,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:otg.mixins.json:MixinChunkManager,pl:mixin:A}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_171] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_171] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_171] {}`
</details>

[AlienJungle.zip](https://github.com/PG85/OpenTerrainGenerator/files/7575559/AlienJungle.zip)

**Comment by PG85** [comment]
Thanks for reporting, fixed for 0.1.4.
